// OFFICE:
// independent item:
import officeBase1 from './assets/office/bas-1-min.jpg';
import officeBase2 from './assets/office/bas-2-min.jpg';
import officeBase3 from './assets/office/bas-3-min.jpg';
import officeBase4 from './assets/office/bas-4-min.jpg';
import officeBase5 from './assets/office/bas-5-min.jpg';
import officeBase6 from './assets/office/bas-6-min.jpg';
import officeBase7 from './assets/office/bas-7-min.jpg';
import officeBase8 from './assets/office/bas-8-min.jpg';

// to review every item:
import officeToShow1 from './assets/office/toShow-1-min.jpg';
import officeToShow2 from './assets/office/toShow-2-min.jpg';
import officeToShow3 from './assets/office/toShow-3-min.jpg';
import officeToShow4 from './assets/office/toShow-4-min.jpg';
import officeToShow5 from './assets/office/toShow-5-min.jpg';
import officeToShow6 from './assets/office/toShow-6-min.jpg';
import officeToShow7 from './assets/office/toShow-7-min.jpg';
import officeToShow8 from './assets/office/toShow-8-min.jpg';
import officeToShow9 from './assets/office/toShow-9-min.jpg';
import officeToShow10 from './assets/office/toShow-10-min.jpg';

// LIVING ROOM
// independent item:

import livingBase1 from './assets/living/bas-1-min.jpg';
import livingBase2 from './assets/living/bas-2-min.jpg';
import livingBase3 from './assets/living/bas-3-min.jpg';
import livingBase4 from './assets/living/bas-4-min.jpg';
import livingBase5 from './assets/living/bas-5-min.jpg';
import livingBase6 from './assets/living/bas-6-min.jpg';
import livingBase7 from './assets/living/bas-7-min.jpg';
import livingBase8 from './assets/living/bas-8-min.jpg';
// to review every item:
import livingToShow1 from './assets/living/toShow-1-min.jpg';
import livingToShow2 from './assets/living/toShow-2-min.jpg';
import livingToShow3 from './assets/living/toShow-3-min.jpg';
import livingToShow4 from './assets/living/toShow-4-min.jpg';
import livingToShow5 from './assets/living/toShow-5-min.jpg';
import livingToShow6 from './assets/living/toShow-6-min.jpg';
import livingToShow7 from './assets/living/toShow-7-min.jpg';
import livingToShow8 from './assets/living/toShow-8-min.jpg';
import livingToShow9 from './assets/living/toShow-9-min.jpg';
import livingToShow10 from './assets/living/toShow-10-min.jpg';

// ENTRYWAY
// independent item:
import entrywayBase1 from './assets/entryway/bas-1-min.jpg';
import entrywayBase2 from './assets/entryway/bas-2-min.jpg';
import entrywayBase3 from './assets/entryway/bas-3-min.jpg';
import entrywayBase4 from './assets/entryway/bas-4-min.jpg';
import entrywayBase5 from './assets/entryway/bas-5-min.jpg';
import entrywayBase6 from './assets/entryway/bas-6-min.jpg';
import entrywayBase7 from './assets/entryway/bas-7-min.jpg';
import entrywayBase8 from './assets/entryway/bas-8-min.jpg';
// to review every item:
import entrywayToShow1 from './assets/entryway/toShow-1-min.jpg';
import entrywayToShow2 from './assets/entryway/toShow-2-min.jpg';
import entrywayToShow3 from './assets/entryway/toShow-3-min.jpg';
import entrywayToShow4 from './assets/entryway/toShow-4-min.jpg';
import entrywayToShow5 from './assets/entryway/toShow-5-min.jpg';
import entrywayToShow6 from './assets/entryway/toShow-6-min.jpg';
import entrywayToShow7 from './assets/entryway/toShow-7-min.jpg';
import entrywayToShow8 from './assets/entryway/toShow-8-min.jpg';
import entrywayToShow9 from './assets/entryway/toShow-9-min.jpg';
import entrywayToShow10 from './assets/entryway/toShow-10-min.jpg';

// BED ROOM
// independent item:
import bedBase1 from './assets/bed/bas-1-min.jpg';
import bedBase2 from './assets/bed/bas-2-min.jpg';
import bedBase3 from './assets/bed/bas-3-min.jpg';
import bedBase4 from './assets/bed/bas-4-min.jpg';
import bedBase5 from './assets/bed/bas-5-min.jpg';
import bedBase6 from './assets/bed/bas-6-min.jpg';
import bedBase7 from './assets/bed/bas-7-min.jpg';
import bedBase8 from './assets/bed/bas-8-min.jpg';
// to review every item:
import bedToShow1 from './assets/bed/toShow-1-min.jpg';
import bedToShow2 from './assets/bed/toShow-2-min.jpg';
import bedToShow3 from './assets/bed/toShow-3-min.jpg';
import bedToShow4 from './assets/bed/toShow-4-min.jpg';
import bedToShow5 from './assets/bed/toShow-5-min.jpg';
import bedToShow6 from './assets/bed/toShow-6-min.jpg';
import bedToShow7 from './assets/bed/toShow-7-min.jpg';
import bedToShow8 from './assets/bed/toShow-8-min.jpg';
import bedToShow9 from './assets/bed/toShow-9-min.jpg';
import bedToShow10 from './assets/bed/toShow-10-min.jpg';

// DECOR
// independent item:
import decorBase1 from './assets/decor/bas-1-min.jpg';
import decorBase2 from './assets/decor/bas-2-min.jpg';
import decorBase3 from './assets/decor/bas-3-min.jpg';
import decorBase4 from './assets/decor/bas-4-min.jpg';
import decorBase5 from './assets/decor/bas-5-min.jpg';
import decorBase6 from './assets/decor/bas-6-min.jpg';
import decorBase7 from './assets/decor/bas-7-min.jpg';
import decorBase8 from './assets/decor/bas-8-min.jpg';
// to review every item:
import decorToShow1 from './assets/decor/toShow-1-min.jpg';
import decorToShow2 from './assets/decor/toShow-2-min.jpg';
import decorToShow3 from './assets/decor/toShow-3-min.jpg';
import decorToShow4 from './assets/decor/toShow-4-min.jpg';
import decorToShow5 from './assets/decor/toShow-5-min.jpg';
import decorToShow6 from './assets/decor/toShow-6-min.jpg';
import decorToShow7 from './assets/decor/toShow-7-min.jpg';
import decorToShow8 from './assets/decor/toShow-8-min.jpg';
import decorToShow9 from './assets/decor/toShow-9-min.jpg';
import decorToShow10 from './assets/decor/toShow-10-min.jpg';

const categories = {
  office: {
    id: 1,
    title: 'office',
    routeName: 'office',
    products: [
      {
        id: 1,
        name: 'office1',
        slug: 'office1',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase1,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 2,
        name: 'office2',
        slug: 'office2',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase2,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 3,
        name: 'office3',
        slug: 'office3',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase3,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 4,
        name: 'office4',
        slug: 'office4',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase4,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 5,
        name: 'office5',
        slug: 'office5',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase5,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 6,
        name: 'office6',
        slug: 'office6',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase6,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 7,
        name: 'office7',
        slug: 'office7',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase7,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
      {
        id: 8,
        name: 'office8',
        slug: 'office8',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: officeBase8,
        featured: false,
        price: 200,
        availableColors: [
          '#ABE188',
          '#F7EF99',
          '#F1BB87',
          '#F78E69',
          '#5D675B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          officeToShow1,
          officeToShow2,
          officeToShow3,
          officeToShow4,
          officeToShow5,
          officeToShow6,
          officeToShow7,
          officeToShow8,
          officeToShow9,
          officeToShow10,
        ],
      },
    ],
  },
  living: {
    id: 2,
    title: 'living room',
    routeName: 'living-room',
    products: [
      {
        id: 1,
        name: 'living1',
        slug: 'living1',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase1,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 2,
        name: 'living2',
        slug: 'living2',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase2,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 3,
        name: 'living3',
        slug: 'living3',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase3,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 4,
        name: 'living4',
        slug: 'living4',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase4,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 5,
        name: 'living5',
        slug: 'living5',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase5,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 6,
        name: 'living6',
        slug: 'living6',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase6,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 7,
        name: 'living7',
        slug: 'living7',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase7,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
      {
        id: 8,
        name: 'living8',
        slug: 'living8',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: livingBase8,
        featured: false,
        price: 200,
        availableColors: [
          '#2B193D',
          '#2C365E',
          '#484D6D',
          '#4B8F8C',
          '#C5979D',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          livingToShow1,
          livingToShow2,
          livingToShow3,
          livingToShow4,
          livingToShow5,
          livingToShow6,
          livingToShow7,
          livingToShow8,
          livingToShow9,
          livingToShow10,
        ],
      },
    ],
  },
  entryway: {
    id: 3,
    title: 'entryway',
    routeName: 'entryway',
    products: [
      {
        id: 1,
        name: 'entryway1',
        slug: 'entryway1',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase1,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 2,
        name: 'entryway2',
        slug: 'entryway2',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase2,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 3,
        name: 'entryway3',
        slug: 'entryway3',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase3,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 4,
        name: 'entryway4',
        slug: 'entryway4',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase4,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 5,
        name: 'entryway5',
        slug: 'entryway5',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase5,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 6,
        name: 'entryway6',
        slug: 'entryway6',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase6,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 7,
        name: 'entryway7',
        slug: 'entryway7',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase7,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
      {
        id: 8,
        name: 'entryway8',
        slug: 'entryway8',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: entrywayBase8,
        featured: false,
        price: 200,
        availableColors: [
          '#000F08',
          '#136F63',
          '#E0CA3C',
          '#F34213',
          '#3E2F5B',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          entrywayToShow1,
          entrywayToShow2,
          entrywayToShow3,
          entrywayToShow4,
          entrywayToShow5,
          entrywayToShow6,
          entrywayToShow7,
          entrywayToShow8,
          entrywayToShow9,
          entrywayToShow10,
        ],
      },
    ],
  },
  bed: {
    id: 4,
    title: 'bed room',
    routeName: 'bed-room',
    products: [
      {
        id: 1,
        name: 'bedroom1',
        slug: 'bedroom1',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase1,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 2,
        name: 'bedroom2',
        slug: 'bedroom2',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase2,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 3,
        name: 'bedroom3',
        slug: 'bedroom3',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase3,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 4,
        name: 'bedroom4',
        slug: 'bedroom4',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase4,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 5,
        name: 'bedroom5',
        slug: 'bedroom5',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase5,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 6,
        name: 'bedroom6',
        slug: 'bedroom6',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase6,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 7,
        name: 'bedroom7',
        slug: 'bedroom7',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase7,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
      {
        id: 8,
        name: 'bedroom8',
        slug: 'bedroom8',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: bedBase8,
        featured: false,
        price: 200,
        availableColors: [
          '#eae2b7',
          '#fcbf49',
          '#f77f00',
          '#d62828',
          '#3a5a40',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          bedToShow1,
          bedToShow2,
          bedToShow3,
          bedToShow4,
          bedToShow5,
          bedToShow6,
          bedToShow7,
          bedToShow8,
          bedToShow9,
          bedToShow10,
        ],
      },
    ],
  },
  decor: {
    id: 5,
    title: 'decor',
    routeName: 'decor',
    products: [
      {
        id: 1,
        name: 'decor1',
        slug: 'decor1',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase1,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 2,
        name: 'decor2',
        slug: 'decor2',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase2,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 3,
        name: 'decor3',
        slug: 'decor3',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase3,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 4,
        name: 'decor4',
        slug: 'decor4',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase4,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 5,
        name: 'decor5',
        slug: 'decor5',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase5,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 6,
        name: 'decor6',
        slug: 'decor6',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase6,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 7,
        name: 'decor7',
        slug: 'decor7',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase7,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
      {
        id: 8,
        name: 'decor8',
        slug: 'decor8',
        description:
          'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
        onlineReturnPoicy:
          'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
        imgUrl: decorBase8,
        featured: false,
        price: 200,
        availableColors: [
          '#2A2B2A',
          '#5E4955',
          '#996888',
          '#C99DA3',
          '#C6DDF0',
        ],
        details: [
          'W 47.2" x D 23.6" x H 17.7"',
          'High Gloss Black or White Lacquer Finish Top',
          'Polished Stainless Steel Base',
          'Matching End Table Available',
          '51 LBS',
        ],
        returnAndExchange: true,
        freeShipping: false,
        images: [
          decorToShow1,
          decorToShow2,
          decorToShow3,
          decorToShow4,
          decorToShow5,
          decorToShow6,
          decorToShow7,
          decorToShow8,
          decorToShow9,
          decorToShow10,
        ],
      },
    ],
  },
};

// limited and new

const limitedAndNew = [
  {
    id: 2,
    name: 'office2',
    slug: 'office2',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: officeBase2,
    featured: false,
    price: 200,
    availableColors: ['#ABE188', '#F7EF99', '#F1BB87', '#F78E69', '#5D675B'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      officeToShow1,
      officeToShow2,
      officeToShow3,
      officeToShow4,
      officeToShow5,
      officeToShow6,
      officeToShow7,
      officeToShow8,
      officeToShow9,
      officeToShow10,
    ],
  },
  {
    id: 4,
    name: 'office4',
    slug: 'office4',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: officeBase4,
    featured: false,
    price: 200,
    availableColors: ['#ABE188', '#F7EF99', '#F1BB87', '#F78E69', '#5D675B'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      officeToShow1,
      officeToShow2,
      officeToShow3,
      officeToShow4,
      officeToShow5,
      officeToShow6,
      officeToShow7,
      officeToShow8,
      officeToShow9,
      officeToShow10,
    ],
  },
  {
    id: 1,
    name: 'living1',
    slug: 'living1',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: livingBase1,
    featured: false,
    price: 200,
    availableColors: ['#2B193D', '#2C365E', '#484D6D', '#4B8F8C', '#C5979D'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      livingToShow1,
      livingToShow2,
      livingToShow3,
      livingToShow4,
      livingToShow5,
      livingToShow6,
      livingToShow7,
      livingToShow8,
      livingToShow9,
      livingToShow10,
    ],
  },
  {
    id: 3,
    name: 'living3',
    slug: 'living3',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: livingBase3,
    featured: false,
    price: 200,
    availableColors: ['#2B193D', '#2C365E', '#484D6D', '#4B8F8C', '#C5979D'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      livingToShow1,
      livingToShow2,
      livingToShow3,
      livingToShow4,
      livingToShow5,
      livingToShow6,
      livingToShow7,
      livingToShow8,
      livingToShow9,
      livingToShow10,
    ],
  },
  {
    id: 6,
    name: 'living6',
    slug: 'living6',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: livingBase6,
    featured: false,
    price: 200,
    availableColors: ['#2B193D', '#2C365E', '#484D6D', '#4B8F8C', '#C5979D'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      livingToShow1,
      livingToShow2,
      livingToShow3,
      livingToShow4,
      livingToShow5,
      livingToShow6,
      livingToShow7,
      livingToShow8,
      livingToShow9,
      livingToShow10,
    ],
  },
  {
    id: 7,
    name: 'living7',
    slug: 'living7',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: livingBase7,
    featured: false,
    price: 200,
    availableColors: ['#2B193D', '#2C365E', '#484D6D', '#4B8F8C', '#C5979D'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      livingToShow1,
      livingToShow2,
      livingToShow3,
      livingToShow4,
      livingToShow5,
      livingToShow6,
      livingToShow7,
      livingToShow8,
      livingToShow9,
      livingToShow10,
    ],
  },
  {
    id: 2,
    name: 'entryway2',
    slug: 'entryway2',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: entrywayBase2,
    featured: false,
    price: 200,
    availableColors: ['#000F08', '#136F63', '#E0CA3C', '#F34213', '#3E2F5B'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      entrywayToShow1,
      entrywayToShow2,
      entrywayToShow3,
      entrywayToShow4,
      entrywayToShow5,
      entrywayToShow6,
      entrywayToShow7,
      entrywayToShow8,
      entrywayToShow9,
      entrywayToShow10,
    ],
  },
  {
    id: 3,
    name: 'entryway3',
    slug: 'entryway3',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: entrywayBase3,
    featured: false,
    price: 200,
    availableColors: ['#000F08', '#136F63', '#E0CA3C', '#F34213', '#3E2F5B'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      entrywayToShow1,
      entrywayToShow2,
      entrywayToShow3,
      entrywayToShow4,
      entrywayToShow5,
      entrywayToShow6,
      entrywayToShow7,
      entrywayToShow8,
      entrywayToShow9,
      entrywayToShow10,
    ],
  },
  {
    id: 6,
    name: 'bedroom6',
    slug: 'bedroom6',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: bedBase6,
    featured: false,
    price: 200,
    availableColors: ['#eae2b7', '#fcbf49', '#f77f00', '#d62828', '#3a5a40'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      bedToShow1,
      bedToShow2,
      bedToShow3,
      bedToShow4,
      bedToShow5,
      bedToShow6,
      bedToShow7,
      bedToShow8,
      bedToShow9,
      bedToShow10,
    ],
  },
  {
    id: 7,
    name: 'bedroom7',
    slug: 'bedroom7',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: bedBase7,
    featured: false,
    price: 200,
    availableColors: ['#eae2b7', '#fcbf49', '#f77f00', '#d62828', '#3a5a40'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      bedToShow1,
      bedToShow2,
      bedToShow3,
      bedToShow4,
      bedToShow5,
      bedToShow6,
      bedToShow7,
      bedToShow8,
      bedToShow9,
      bedToShow10,
    ],
  },
  {
    id: 7,
    name: 'decor7',
    slug: 'decor7',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: decorBase7,
    featured: false,
    price: 200,
    availableColors: ['#2A2B2A', '#5E4955', '#996888', '#C99DA3', '#C6DDF0'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      decorToShow1,
      decorToShow2,
      decorToShow3,
      decorToShow4,
      decorToShow5,
      decorToShow6,
      decorToShow7,
      decorToShow8,
      decorToShow9,
      decorToShow10,
    ],
  },
  {
    id: 8,
    name: 'decor8',
    slug: 'decor8',
    description:
      'Stunning elegance and a floating desktop define the elite 79-inch Ford Desk. The finish is a smooth black stain over an American oak wood veneer. This is accented with silver painted wood feet and risers plus a black panel on top with ports for wire management. It features four drawers with ball bearing slides for ample and effortless storage at your fingertips. Each pedestal features a dual lock with a top drawer for general storage and the lower drawer with filing that fits both letter and legal files. To finish it off there is a wide keyboard tray that can also double as a notepad storage. Please note: Credenza shown is sold separately.',
    onlineReturnPoicy:
      'We offer 30 days from delivery for an exchange or refund, less original delivery fees on select items. For full return policy information, please click here.',
    imgUrl: decorBase8,
    featured: false,
    price: 200,
    availableColors: ['#2A2B2A', '#5E4955', '#996888', '#C99DA3', '#C6DDF0'],
    details: [
      'W 47.2" x D 23.6" x H 17.7"',
      'High Gloss Black or White Lacquer Finish Top',
      'Polished Stainless Steel Base',
      'Matching End Table Available',
      '51 LBS',
    ],
    returnAndExchange: true,
    freeShipping: false,
    images: [
      decorToShow1,
      decorToShow2,
      decorToShow3,
      decorToShow4,
      decorToShow5,
      decorToShow6,
      decorToShow7,
      decorToShow8,
      decorToShow9,
      decorToShow10,
    ],
  },
];

export { categories, limitedAndNew };
